sudo: required

language: c

before_install:
 - pwd
 - mkdir libatlas
 - curl -O http://www.netlib.org/lapack/lapack-3.6.0.tgz
 - sudo apt-get update -qq
 - sudo apt-get install -qq txt2man
 - sudo apt-get install -qq gfortran
 - make
 - cd TEST

install:
 - make

script:
 - cd ATLAS
 - mkdir BLDdir
 - cd BLDdir
 - ../configure --prefix=~/libatlas --with-netlib-lapack-tarfile=~/lapack-3.6.0.tgz
 - make build
 - make test
