sudo: required

language: c

before_install:
 - pwd
 - mkdir libatlas
 - curl -O http://www.netlib.org/lapack/lapack-3.6.0.tgz
 - sudo apt-get install txt2man gfortran
 - make
 - cd TEST

install:
 - make

script:
 - cd ATLAS
 - mkdir BLDdir
 - cd BLDdir
 - ../configure --prefix=~/libatlas --with-netlib-lapack-tarfile=~/lapack-3.6.0.tgz
 - make build
 - make test
